# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x0c\x66iletransfer\"\x19\n\tFileChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"2\n\x0eTransferStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"<\n\tEndSignal\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06value1\x18\x02 \x03(\x01\x12\x0e\n\x06value2\x18\x03 \x03(\x01\"/\n\x0b\x45ndResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa5\x01\n\x13\x46ileTransferService\x12\x45\n\x08SendFile\x12\x17.filetransfer.FileChunk\x1a\x1c.filetransfer.TransferStatus\"\x00(\x01\x12G\n\x0f\x45ndFileTransfer\x12\x17.filetransfer.EndSignal\x1a\x19.filetransfer.EndResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILECHUNK']._serialized_start=28
  _globals['_FILECHUNK']._serialized_end=53
  _globals['_TRANSFERSTATUS']._serialized_start=55
  _globals['_TRANSFERSTATUS']._serialized_end=105
  _globals['_ENDSIGNAL']._serialized_start=107
  _globals['_ENDSIGNAL']._serialized_end=167
  _globals['_ENDRESPONSE']._serialized_start=169
  _globals['_ENDRESPONSE']._serialized_end=216
  _globals['_FILETRANSFERSERVICE']._serialized_start=219
  _globals['_FILETRANSFERSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
